# output paths for hydra logs
run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
    dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
defaults:
    - override job_logging: custom
