# @package _global_
checkpoint: ???

metrics:
  - _target_: src.model.metric.accuracy
  - _target_: src.model.metric.top_k_acc

# specify here default training configuration
defaults:
    - model: mnist_lenet
    - hparams: lenet_baseline
    - data_loader: mnist_train
    - status: train

    # override job logging to custom!
    - override hydra/job_logging: custom
    # - override hydra/hydra_logging: colorlog

# path to original working directory (that `run.py` was executed from in command line)
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have path to original work dir as a special variable
# read more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra.runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

save_dir: saved/

hydra:
    # output paths for hydra logs
    run:
        dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    sweep:
        dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
        subdir: ${hydra.job.num}

    job:
        # you can set here environment variables that are universal for all users
        # for system specific variables (like data paths) it's better to use .env file!
        env_set:
            # currently there are some issues with running sweeps alongside wandb
            # https://github.com/wandb/client/issues/1314
            # this env var fixes that
            WANDB_START_METHOD: thread
