# @package constant

# Time Series begin year month
beg:
  year: 1979
  month: 1

# Time Series end year month
end:
  year: 2020
  month: 12

# month used for comparison, here April used
month_compared: 4

# gdal option
gdal:
  nodata: -9.223372e+18
